### PR TITLE
chore: fetch button related changes

### PR DESCRIPTION
**Pull request by tahmidrahman-dsi**
Opening the PR for the visibility of the changes required for configuring fetch button

### CODE REVIEW

**Comment by rikukissa** [comment]
Your environment is deployed to https://ocrvs-7489-http-button.opencrvs.dev.

**Comment by tahmidrahman-dsi** [comment]
Thanks @rikukissa now I checked, the button is there. However, the endpoint is not found and the error is not also shown 🤔  will work on it later today

**Comment by Zangetsu101** [comment]
@tahmidrahman-dsi we can close this right?

**Comment by tahmidrahman-dsi** [comment]
> @tahmidrahman-dsi we can close this right?

Yes

**Pull request closed without merging**
