### PR TITLE
[OCRVS-6971] Message updates for dynamic maxSize

### PR DESCRIPTION
**Pull request by tahmidrahman-dsi**

### CODE REVIEW

**Comment by Zangetsu101** [comment]
@tahmidrahman-dsi let's move this to countryconfig please

**Review by Zangetsu101 — CHANGES_REQUESTED** [review]
The types for the "DOCUMENT_UPLOADER_WITH_OPTIONS" need to be updated

**Comment by tahmidrahman-dsi** [comment]
> @tahmidrahman-dsi let's move this to countryconfig please

@Zangetsu101 done https://github.com/opencrvs/opencrvs-countryconfig/pull/132

**Comment by Zangetsu101** [comment]
Thanks I'm closing this one then

**Pull request closed without merging**
